### ISSUE TITLE
How to use php variable in attributes?

### ISSUE THREAD

**Issue by OnkelTem** [viniwrubleski/jade-php#11]
Consider this code:

```
html(lang!="<?php $language->language?>")
```

I expected jade php should support this or similar syntax:

```
html(lang!="$language->language")
```

but currently it seems there's no way to use it.

Help? Ideas?

**Comment by OnkelTem** [comment]
Also it should support syntax like:

```
html("$attributes")
```

to expand it to:

``` html
<html <?php echo $attributes; ?></html>
```

**Comment by OnkelTem** [comment]
dupe of https://github.com/viniwrubleski/jade-php/issues/5

**Comment by adam-cyclones** [comment]
I have a workaround:

Add a local variable into the compiler function wherever you have it, for example in gulp-jade you might find it inside:

```
gulp.src("some/src")
.pipe(jade({locals:{some:"value"}}))
```

This variable is going to be a function that can be called in all of your jade files. Lets focus on the jade function as seen above inside a pipe in that example.

### JS new function:

```
jade(locals:{
        $:function(str){
            return "<?php print $"+str+" ?>"
        }
    })
```

### JADE usage:

```
h1(class!=$(php_variable))
```

### COMPILES

```
<h1 class="<?php print php_variable?>"></h1>
```

**Comment by OnkelTem** [comment]
Well, smart enough!

My _workaround_ was switching to https://github.com/SE7ENSKY/jade2php 
It is a completely different thing and allows you work with PHP variables like they were a Jade variables, e.g.:

``` jade
#main.row
  if tabs
    .tabs.row.reg!= render(tabs)
  != render(page['content'])
```

**Comment by adam-cyclones** [comment]
That's actually what if been searching for OnkelTem bug couldn't find something like it, I'm building an automated theme builder for Drupal and I think your workaround may remove the pain of having to think in php JS / jade all at once. Thanks!

**Comment by OnkelTem** [comment]
Oh, man! That's what I was doing too. But  I think I've already done most of the building framework and I can share its main ideas. At least it may save you some time. There are caveats in jade2php for example.

Dunno about PM-abilities of github, so this is my eml: aneganov attt gmail ddot com. Drop me a line.

**Comment by feliperohde** [comment]
- foreach(get_categories('show_count=0&title_li=&hide_empty=0&exclude=1') as $category){
  
    li
      a(href= get_category_link( $category->term_id))= $category->name
  - }

causes:

Unexpected token >
